-- Run only against the disposable CI database.
\set ON_ERROR_STOP on

BEGIN;
SET LOCAL search_path TO virginia_dev_saayam_rdbms, public;

DO $$
DECLARE
    test_user_id VARCHAR(255);
    skill_count INTEGER;
BEGIN
    INSERT INTO help_categories (cat_id, cat_name, cat_desc)
    VALUES
        ('CI_EDUCATION', 'CI Education', 'Test education category'),
        ('CI_LOGISTICS', 'CI Logistics', 'Test logistics category');

    -- Capture the ID generated by the users trigger.
    INSERT INTO users (full_name)
    VALUES ('CI Test Volunteer')
    RETURNING user_id INTO test_user_id;

    INSERT INTO volunteer_applications (
        user_id,
        application_status
    )
    VALUES (test_user_id, 'STARTED');

    UPDATE volunteer_applications
    SET current_page = 2,
        govt_id_path = 'https://example.invalid/ci-id.jpg',
        application_status = 'IN_REVIEW',
        skill_codes = '["CI_EDUCATION", "CI_LOGISTICS"]'::JSON,
        availability = '{
            "days": ["Monday", "Wednesday"],
            "time": ["2025-12-24 23:17:20.929643"]
        }'::JSONB,
        terms_and_conditions = TRUE
    WHERE user_id = test_user_id;

    IF NOT EXISTS (
        SELECT 1 FROM volunteer_applications
        WHERE user_id = test_user_id
          AND current_page = 2
          AND application_status = 'IN_REVIEW'
          AND terms_and_conditions IS TRUE
    ) THEN
        RAISE EXCEPTION 'Application update failed';
    END IF;

    -- Acceptance should transfer details and skills,
    -- then remove the original application.
    UPDATE volunteer_applications
    SET application_status = 'ACCEPTED'
    WHERE user_id = test_user_id;

    IF NOT EXISTS (
        SELECT 1 FROM volunteer_details
        WHERE user_id = test_user_id
          AND terms_and_conditions IS TRUE
          AND govt_id_path1 = 'https://example.invalid/ci-id.jpg'
          AND availability_days = '["Monday", "Wednesday"]'::JSONB
          AND availability_times =
              '["2025-12-24 23:17:20.929643"]'::JSONB
    ) THEN
        RAISE EXCEPTION 'Volunteer details were not transferred correctly';
    END IF;

    SELECT COUNT(*) INTO skill_count
    FROM user_skills
    WHERE user_id = test_user_id;

    IF skill_count <> 2 THEN
        RAISE EXCEPTION 'Expected 2 transferred skills, found %',
            skill_count;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM user_skills
        WHERE user_id = test_user_id AND cat_id = 'CI_EDUCATION'
    ) OR NOT EXISTS (
        SELECT 1 FROM user_skills
        WHERE user_id = test_user_id AND cat_id = 'CI_LOGISTICS'
    ) THEN
        RAISE EXCEPTION 'Expected skill categories were not transferred';
    END IF;

    IF EXISTS (
        SELECT 1 FROM volunteer_applications
        WHERE user_id = test_user_id
    ) THEN
        RAISE EXCEPTION 'Accepted application was not removed';
    END IF;

    RAISE NOTICE 'PASS: Volunteer onboarding checks passed';
END;
$$;

-- Remove test rows after successful verification.
ROLLBACK;